services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../src:/app/src
      - ../dashboard:/app/dashboard
      - ../configs:/app/configs
      - ../tests:/app/tests
      - ../results:/app/results
      - ../Real-Car-Data-And-Stats:/app/Real-Car-Data-And-Stats
    environment:
      - DASH_DEBUG=true
